version: "3"
services:
  testing-mysql:
    image: mysql:8.0.23
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ems
      MYSQL_USER: emsadmin
      MYSQL_PASSWORD: password
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql

  testing-mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./mongodb:/data/db
      - ./script/init.js:/docker-entrypoint-initdb.d/init.js